import { IEmoji } from "./interface";

export const emojiData: IEmoji[] = [
  {
    emoji: "😀",
    keywords: ["grinning_face", "face", "smile", "happy", "joy", ":D", "grin"],
    category: "people"
  },
  {
    emoji: "😃",
    keywords: [
      "grinning_face_with_big_eyes",
      "face",
      "happy",
      "joy",
      "haha",
      ":D",
      ":)",
      "smile",
      "funny",
    ],
    category: "people"
  },
  {
    emoji: "😄",
    keywords: [
      "grinning_face_with_smiling_eyes",
      "face",
      "happy",
      "joy",
      "funny",
      "haha",
      "laugh",
      "like",
      ":D",
      ":)",
      "smile",
    ],
  },
  {
    emoji: "😁",
    keywords: [
      "beaming_face_with_smiling_eyes",
      "face",
      "happy",
      "smile",
      "joy",
      "kawaii",
    ],
  },
  {
    emoji: "😆",
    keywords: [
      "grinning_squinting_face",
      "happy",
      "joy",
      "lol",
      "satisfied",
      "haha",
      "face",
      "glad",
      "XD",
      "laugh",
    ],
  },
  {
    emoji: "😅",
    keywords: [
      "grinning_face_with_sweat",
      "face",
      "hot",
      "happy",
      "laugh",
      "sweat",
      "smile",
      "relief",
    ],
  },
  {
    emoji: "🤣",
    keywords: [
      "rolling_on_the_floor_laughing",
      "face",
      "rolling",
      "floor",
      "laughing",
      "lol",
      "haha",
      "rofl",
    ],
  },
  {
    emoji: "😂",
    keywords: [
      "face_with_tears_of_joy",
      "face",
      "cry",
      "tears",
      "weep",
      "happy",
      "happytears",
      "haha",
    ],
  },
  {
    emoji: "🙂",
    keywords: ["slightly_smiling_face", "face", "smile"],
  },
  {
    emoji: "🙃",
    keywords: ["upside_down_face", "face", "flipped", "silly", "smile"],
  },
  {
    emoji: "😉",
    keywords: [
      "winking_face",
      "face",
      "happy",
      "mischievous",
      "secret",
      ";)",
      "smile",
      "eye",
    ],
  },
  {
    emoji: "😊",
    keywords: [
      "smiling_face_with_smiling_eyes",
      "face",
      "smile",
      "happy",
      "flushed",
      "crush",
      "embarrassed",
      "shy",
      "joy",
    ],
  },
  {
    emoji: "😇",
    keywords: [
      "smiling_face_with_halo",
      "face",
      "angel",
      "heaven",
      "halo",
      "innocent",
    ],
  },
  {
    emoji: "🥰",
    keywords: [
      "smiling_face_with_hearts",
      "face",
      "love",
      "like",
      "affection",
      "valentines",
      "infatuation",
      "crush",
      "hearts",
      "adore",
    ],
  },
  {
    emoji: "😍",
    keywords: [
      "smiling_face_with_heart_eyes",
      "face",
      "love",
      "like",
      "affection",
      "valentines",
      "infatuation",
      "crush",
      "heart",
    ],
  },
  {
    emoji: "🤩",
    keywords: ["star_struck", "face", "smile", "starry", "eyes", "grinning"],
  },
  {
    emoji: "😘",
    keywords: [
      "face_blowing_a_kiss",
      "face",
      "love",
      "like",
      "affection",
      "valentines",
      "infatuation",
      "kiss",
    ],
  },
  {
    emoji: "😗",
    keywords: [
      "kissing_face",
      "love",
      "like",
      "face",
      "3",
      "valentines",
      "infatuation",
      "kiss",
    ],
  },
  {
    emoji: "☺️",
    keywords: ["smiling_face", "face", "blush", "massage", "happiness"],
  },
  {
    emoji: "😚",
    keywords: [
      "kissing_face_with_closed_eyes",
      "face",
      "love",
      "like",
      "affection",
      "valentines",
      "infatuation",
      "kiss",
    ],
  },
  {
    emoji: "😙",
    keywords: [
      "kissing_face_with_smiling_eyes",
      "face",
      "affection",
      "valentines",
      "infatuation",
      "kiss",
    ],
  },
  {
    emoji: "😋",
    keywords: [
      "face_savoring_food",
      "happy",
      "joy",
      "tongue",
      "smile",
      "face",
      "silly",
      "yummy",
      "nom",
      "delicious",
      "savouring",
    ],
  },
  {
    emoji: "😛",
    keywords: [
      "face_with_tongue",
      "face",
      "prank",
      "childish",
      "playful",
      "mischievous",
      "smile",
      "tongue",
    ],
  },
  {
    emoji: "😜",
    keywords: [
      "winking_face_with_tongue",
      "face",
      "prank",
      "childish",
      "playful",
      "mischievous",
      "smile",
      "wink",
      "tongue",
    ],
  },
  {
    emoji: "🤪",
    keywords: ["zany_face", "face", "goofy", "crazy"],
  },
  {
    emoji: "😝",
    keywords: [
      "squinting_face_with_tongue",
      "face",
      "prank",
      "playful",
      "mischievous",
      "smile",
      "tongue",
    ],
  },
  {
    emoji: "🤑",
    keywords: ["money_mouth_face", "face", "rich", "dollar", "money"],
  },
  {
    emoji: "🤗",
    keywords: ["hugging_face", "face", "smile", "hug"],
  },
  {
    emoji: "🤭",
    keywords: [
      "face_with_hand_over_mouth",
      "face",
      "whoops",
      "shock",
      "surprise",
    ],
  },
  {
    emoji: "🤫",
    keywords: ["shushing_face", "face", "quiet", "shhh"],
  },
  {
    emoji: "🤔",
    keywords: ["thinking_face", "face", "hmmm", "think", "consider"],
  },
  {
    emoji: "🤐",
    keywords: ["zipper_mouth_face", "face", "sealed", "zipper", "secret"],
  },
  {
    emoji: "🤨",
    keywords: [
      "face_with_raised_eyebrow",
      "face",
      "distrust",
      "scepticism",
      "disapproval",
      "disbelief",
      "surprise",
      "suspicious",
    ],
  },
  {
    emoji: "😐",
    keywords: ["neutral_face", "indifference", "meh", ":|", "neutral"],
  },
  {
    emoji: "😑",
    keywords: [
      "expressionless_face",
      "face",
      "indifferent",
      "-_-",
      "meh",
      "deadpan",
    ],
  },
  {
    emoji: "😶",
    keywords: ["face_without_mouth", "face"],
  },
  {
    emoji: "😏",
    keywords: [
      "smirking_face",
      "face",
      "smile",
      "mean",
      "prank",
      "smug",
      "sarcasm",
    ],
  },
  {
    emoji: "😒",
    keywords: [
      "unamused_face",
      "indifference",
      "bored",
      "straight face",
      "serious",
      "sarcasm",
      "unimpressed",
      "skeptical",
      "dubious",
      "ugh",
      "side_eye",
    ],
  },
  {
    emoji: "🙄",
    keywords: ["face_with_rolling_eyes", "face", "eyeroll", "frustrated"],
  },
  {
    emoji: "😬",
    keywords: ["grimacing_face", "face", "grimace", "teeth"],
  },
  {
    emoji: "🤥",
    keywords: ["lying_face", "face", "lie", "pinocchio"],
  },
  {
    emoji: "😌",
    keywords: [
      "relieved_face",
      "face",
      "relaxed",
      "phew",
      "massage",
      "happiness",
    ],
  },
  {
    emoji: "😔",
    keywords: ["pensive_face", "face", "sad", "depressed", "upset"],
  },
  {
    emoji: "😪",
    keywords: ["sleepy_face", "face", "tired", "rest", "nap"],
  },
  {
    emoji: "🤤",
    keywords: ["drooling_face", "face"],
  },
  {
    emoji: "😴",
    keywords: ["sleeping_face", "face", "tired", "sleepy", "night", "zzz"],
  },
  {
    emoji: "😷",
    keywords: [
      "face_with_medical_mask",
      "face",
      "sick",
      "ill",
      "disease",
      "covid",
    ],
  },
  {
    emoji: "🤒",
    keywords: [
      "face_with_thermometer",
      "sick",
      "temperature",
      "thermometer",
      "cold",
      "fever",
      "covid",
    ],
  },
  {
    emoji: "🤕",
    keywords: [
      "face_with_head_bandage",
      "injured",
      "clumsy",
      "bandage",
      "hurt",
    ],
  },
  {
    emoji: "🤢",
    keywords: [
      "nauseated_face",
      "face",
      "vomit",
      "gross",
      "green",
      "sick",
      "throw up",
      "ill",
    ],
  },
  {
    emoji: "🤮",
    keywords: ["face_vomiting", "face", "sick"],
  },
  {
    emoji: "🤧",
    keywords: [
      "sneezing_face",
      "face",
      "gesundheit",
      "sneeze",
      "sick",
      "allergy",
    ],
  },
  {
    emoji: "🥵",
    keywords: ["hot_face", "face", "feverish", "heat", "red", "sweating"],
  },
  {
    emoji: "🥶",
    keywords: [
      "cold_face",
      "face",
      "blue",
      "freezing",
      "frozen",
      "frostbite",
      "icicles",
    ],
  },
  {
    emoji: "🥴",
    keywords: ["woozy_face", "face", "dizzy", "intoxicated", "tipsy", "wavy"],
  },
  {
    emoji: "😵",
    keywords: ["dizzy_face", "spent", "unconscious", "xox", "dizzy"],
  },
  {
    emoji: "🤯",
    keywords: ["exploding_head", "face", "shocked", "mind", "blown"],
  },
  {
    emoji: "🤠",
    keywords: ["cowboy_hat_face", "face", "cowgirl", "hat"],
  },
  {
    emoji: "🥳",
    keywords: ["partying_face", "face", "celebration", "woohoo"],
  },
  {
    emoji: "😎",
    keywords: [
      "smiling_face_with_sunglasses",
      "face",
      "cool",
      "smile",
      "summer",
      "beach",
      "sunglass",
    ],
  },
  {
    emoji: "🤓",
    keywords: ["nerd_face", "face", "nerdy", "geek", "dork"],
  },
  {
    emoji: "🧐",
    keywords: ["face_with_monocle", "face", "stuffy", "wealthy"],
  },
  {
    emoji: "😕",
    keywords: [
      "confused_face",
      "face",
      "indifference",
      "huh",
      "weird",
      "hmmm",
      ":/",
    ],
  },
  {
    emoji: "😟",
    keywords: ["worried_face", "face", "concern", "nervous", ":("],
  },
  {
    emoji: "🙁",
    keywords: [
      "slightly_frowning_face",
      "face",
      "frowning",
      "disappointed",
      "sad",
      "upset",
    ],
  },
  {
    emoji: "☹️",
    keywords: ["frowning_face", "face", "sad", "upset", "frown"],
  },
  {
    emoji: "😮",
    keywords: [
      "face_with_open_mouth",
      "face",
      "surprise",
      "impressed",
      "wow",
      "whoa",
      ":O",
    ],
  },
  {
    emoji: "😯",
    keywords: ["hushed_face", "face", "woo", "shh"],
  },
  {
    emoji: "😲",
    keywords: ["astonished_face", "face", "xox", "surprised", "poisoned"],
  },
  {
    emoji: "😳",
    keywords: ["flushed_face", "face", "blush", "shy", "flattered"],
  },
  {
    emoji: "🥺",
    keywords: [
      "pleading_face",
      "face",
      "begging",
      "mercy",
      "cry",
      "tears",
      "sad",
      "grievance",
    ],
  },
  {
    emoji: "😦",
    keywords: ["frowning_face_with_open_mouth", "face", "aw", "what"],
  },
  {
    emoji: "😧",
    keywords: ["anguished_face", "face", "stunned", "nervous"],
  },
  {
    emoji: "😨",
    keywords: ["fearful_face", "face", "scared", "terrified", "nervous"],
  },
  {
    emoji: "😰",
    keywords: ["anxious_face_with_sweat", "face", "nervous", "sweat"],
  },
  {
    emoji: "😥",
    keywords: ["sad_but_relieved_face", "face", "phew", "sweat", "nervous"],
  },
  {
    emoji: "😢",
    keywords: [
      "crying_face",
      "face",
      "tears",
      "sad",
      "depressed",
      "upset",
      ":'(",
    ],
  },
  {
    emoji: "😭",
    keywords: [
      "loudly_crying_face",
      "sobbing",
      "face",
      "cry",
      "tears",
      "sad",
      "upset",
      "depressed",
    ],
  },
  {
    emoji: "😱",
    keywords: ["face_screaming_in_fear", "face", "munch", "scared", "omg"],
  },
  {
    emoji: "😖",
    keywords: [
      "confounded_face",
      "face",
      "confused",
      "sick",
      "unwell",
      "oops",
      ":S",
    ],
  },
  {
    emoji: "😣",
    keywords: ["persevering_face", "face", "sick", "no", "upset", "oops"],
  },
  {
    emoji: "😞",
    keywords: ["disappointed_face", "face", "sad", "upset", "depressed", ":("],
  },
  {
    emoji: "😓",
    keywords: [
      "downcast_face_with_sweat",
      "face",
      "hot",
      "sad",
      "tired",
      "exercise",
    ],
  },
  {
    emoji: "😩",
    keywords: [
      "weary_face",
      "face",
      "tired",
      "sleepy",
      "sad",
      "frustrated",
      "upset",
    ],
  },
  {
    emoji: "😫",
    keywords: ["tired_face", "sick", "whine", "upset", "frustrated"],
  },
  {
    emoji: "🥱",
    keywords: ["yawning_face", "tired", "sleepy"],
  },
  {
    emoji: "😤",
    keywords: [
      "face_with_steam_from_nose",
      "face",
      "gas",
      "phew",
      "proud",
      "pride",
      "triumph",
    ],
  },
  {
    emoji: "😡",
    keywords: ["pouting_face", "angry", "mad", "hate", "despise"],
  },
  {
    emoji: "😠",
    keywords: ["angry_face", "mad", "face", "annoyed", "frustrated"],
  },
  {
    emoji: "🤬",
    keywords: [
      "face_with_symbols_on_mouth",
      "face",
      "swearing",
      "cursing",
      "cussing",
      "profanity",
      "expletive",
    ],
  },
  {
    emoji: "😈",
    keywords: ["smiling_face_with_horns", "devil", "horns"],
  },
  {
    emoji: "👿",
    keywords: ["angry_face_with_horns", "devil", "angry", "horns"],
  },
  {
    emoji: "💀",
    keywords: ["skull", "dead", "skeleton", "creepy", "death", "dead"],
  },
  {
    emoji: "☠️",
    keywords: [
      "skull_and_crossbones",
      "poison",
      "danger",
      "deadly",
      "scary",
      "death",
      "pirate",
      "evil",
    ],
  },
  {
    emoji: "💩",
    keywords: ["pile_of_poo", "hankey", "shitface", "fail", "turd", "shit"],
  },
  {
    emoji: "🤡",
    keywords: ["clown_face", "face"],
  },
  {
    emoji: "👹",
    keywords: [
      "ogre",
      "monster",
      "red",
      "mask",
      "halloween",
      "scary",
      "creepy",
      "devil",
      "demon",
      "japanese_ogre",
    ],
  },
  {
    emoji: "👺",
    keywords: [
      "goblin",
      "red",
      "evil",
      "mask",
      "monster",
      "scary",
      "creepy",
      "japanese_goblin",
    ],
  },
  {
    emoji: "👻",
    keywords: ["ghost", "halloween", "spooky", "scary"],
  },
  {
    emoji: "👽",
    keywords: ["alien", "UFO", "paul", "weird", "outer_space"],
  },
  {
    emoji: "👾",
    keywords: ["alien_monster", "game", "arcade", "play"],
  },
  {
    emoji: "🤖",
    keywords: ["robot", "computer", "machine", "bot"],
  },
  {
    emoji: "😺",
    keywords: ["grinning_cat", "animal", "cats", "happy", "smile"],
  },
  {
    emoji: "😸",
    keywords: ["grinning_cat_with_smiling_eyes", "animal", "cats", "smile"],
  },
  {
    emoji: "😹",
    keywords: [
      "cat_with_tears_of_joy",
      "animal",
      "cats",
      "haha",
      "happy",
      "tears",
    ],
  },
  {
    emoji: "😻",
    keywords: [
      "smiling_cat_with_heart_eyes",
      "animal",
      "love",
      "like",
      "affection",
      "cats",
      "valentines",
      "heart",
    ],
  },
  {
    emoji: "😼",
    keywords: ["cat_with_wry_smile", "animal", "cats", "smirk"],
  },
  {
    emoji: "😽",
    keywords: ["kissing_cat", "animal", "cats", "kiss"],
  },
  {
    emoji: "🙀",
    keywords: ["weary_cat", "animal", "cats", "munch", "scared", "scream"],
  },
  {
    emoji: "😿",
    keywords: [
      "crying_cat",
      "animal",
      "tears",
      "weep",
      "sad",
      "cats",
      "upset",
      "cry",
    ],
  },
  {
    emoji: "😾",
    keywords: ["pouting_cat", "animal", "cats"],
  },
  {
    emoji: "🙈",
    keywords: ["see_no_evil_monkey", "monkey", "animal", "nature", "haha"],
  },
  {
    emoji: "🙉",
    keywords: ["hear_no_evil_monkey", "animal", "monkey", "nature"],
  },
  {
    emoji: "🙊",
    keywords: ["speak_no_evil_monkey", "monkey", "animal", "nature", "omg"],
  },
  {
    emoji: "💋",
    keywords: [
      "kiss_mark",
      "face",
      "lips",
      "love",
      "like",
      "affection",
      "valentines",
    ],
  },
  {
    emoji: "💌",
    keywords: [
      "love_letter",
      "email",
      "like",
      "affection",
      "envelope",
      "valentines",
    ],
  },
  {
    emoji: "💘",
    keywords: [
      "heart_with_arrow",
      "love",
      "like",
      "heart",
      "affection",
      "valentines",
    ],
  },
  {
    emoji: "💝",
    keywords: ["heart_with_ribbon", "love", "valentines"],
  },
  {
    emoji: "💖",
    keywords: ["sparkling_heart", "love", "like", "affection", "valentines"],
  },
  {
    emoji: "💗",
    keywords: [
      "growing_heart",
      "like",
      "love",
      "affection",
      "valentines",
      "pink",
    ],
  },
  {
    emoji: "💓",
    keywords: [
      "beating_heart",
      "love",
      "like",
      "affection",
      "valentines",
      "pink",
      "heart",
    ],
  },
  {
    emoji: "💞",
    keywords: ["revolving_hearts", "love", "like", "affection", "valentines"],
  },
  {
    emoji: "💕",
    keywords: [
      "two_hearts",
      "love",
      "like",
      "affection",
      "valentines",
      "heart",
    ],
  },
  {
    emoji: "💟",
    keywords: ["heart_decoration", "purple-square", "love", "like"],
  },
  {
    emoji: "❣️",
    keywords: ["heart_exclamation", "decoration", "love"],
  },
  {
    emoji: "💔",
    keywords: ["broken_heart", "sad", "sorry", "break", "heart", "heartbreak"],
  },
  {
    emoji: "❤️",
    keywords: ["red_heart", "love", "like", "valentines"],
  },
  {
    emoji: "🧡",
    keywords: ["orange_heart", "love", "like", "affection", "valentines"],
  },
  {
    emoji: "💛",
    keywords: ["yellow_heart", "love", "like", "affection", "valentines"],
  },
  {
    emoji: "💚",
    keywords: ["green_heart", "love", "like", "affection", "valentines"],
  },
  {
    emoji: "💙",
    keywords: ["blue_heart", "love", "like", "affection", "valentines"],
  },
  {
    emoji: "💜",
    keywords: ["purple_heart", "love", "like", "affection", "valentines"],
  },
  {
    emoji: "🤎",
    keywords: ["brown_heart", "coffee"],
  },
  {
    emoji: "🖤",
    keywords: ["black_heart", "evil"],
  },
  {
    emoji: "🤍",
    keywords: ["white_heart", "pure"],
  },
  {
    emoji: "💯",
    keywords: [
      "hundred_points",
      "score",
      "perfect",
      "numbers",
      "century",
      "exam",
      "quiz",
      "test",
      "pass",
      "hundred",
      "100",
    ],
  },
  {
    emoji: "💢",
    keywords: ["anger_symbol", "angry", "mad"],
  },
  {
    emoji: "💥",
    keywords: ["collision", "bomb", "explode", "explosion", "blown"],
  },
  {
    emoji: "💫",
    keywords: ["dizzy", "star", "sparkle", "shoot", "magic"],
  },
  {
    emoji: "💦",
    keywords: ["sweat_droplets", "water", "drip", "oops"],
  },
  {
    emoji: "💨",
    keywords: [
      "dashing_away",
      "wind",
      "air",
      "fast",
      "shoo",
      "fart",
      "smoke",
      "puff",
    ],
  },
  {
    emoji: "🕳️",
    keywords: ["hole", "embarrassing"],
  },
  {
    emoji: "💣",
    keywords: ["bomb", "boom", "explode", "explosion", "terrorism"],
  },
  {
    emoji: "💬",
    keywords: [
      "speech_balloon",
      "bubble",
      "words",
      "message",
      "talk",
      "chatting",
    ],
  },
  {
    emoji: "👁️‍🗨️",
    keywords: ["eye_in_speech_bubble", "info"],
  },
  {
    emoji: "🗨️",
    keywords: ["left_speech_bubble", "words", "message", "talk", "chatting"],
  },
  {
    emoji: "🗯️",
    keywords: ["right_anger_bubble", "caption", "speech", "thinking", "mad"],
  },
  {
    emoji: "💭",
    keywords: [
      "thought_balloon",
      "bubble",
      "cloud",
      "speech",
      "thinking",
      "dream",
    ],
  },
  {
    emoji: "💤",
    keywords: ["zzz", "sleepy", "tired", "dream"],
  },
  {
    emoji: "👋",
    keywords: [
      "waving_hand",
      "wave",
      "hands",
      "gesture",
      "goodbye",
      "solong",
      "farewell",
      "hello",
      "hi",
      "palm",
    ],
  },
  {
    emoji: "🤚",
    keywords: ["raised_back_of_hand", "fingers", "raised", "backhand"],
  },
  {
    emoji: "🖐️",
    keywords: ["hand_with_fingers_splayed", "hand", "fingers", "palm"],
  },
  {
    emoji: "✋",
    keywords: ["raised_hand", "fingers", "stop", "highfive", "palm", "ban"],
  },
  {
    emoji: "🖖",
    keywords: ["vulcan_salute", "hand", "fingers", "spock", "star trek"],
  },
  {
    emoji: "👌",
    keywords: ["ok_hand", "fingers", "limbs", "perfect", "ok", "okay"],
  },
  {
    emoji: "🤏",
    keywords: ["pinching_hand", "tiny", "small", "size"],
  },
  {
    emoji: "✌️",
    keywords: [
      "victory_hand",
      "fingers",
      "ohyeah",
      "hand",
      "peace",
      "victory",
      "two",
    ],
  },
  {
    emoji: "🤞",
    keywords: ["crossed_fingers", "good", "lucky"],
  },
  {
    emoji: "🤟",
    keywords: ["love_you_gesture", "hand", "fingers", "gesture"],
  },
  {
    emoji: "🤘",
    keywords: [
      "sign_of_the_horns",
      "hand",
      "fingers",
      "evil_eye",
      "sign_of_horns",
      "rock_on",
    ],
  },
  {
    emoji: "🤙",
    keywords: ["call_me_hand", "hands", "gesture", "shaka"],
  },
  {
    emoji: "👈",
    keywords: [
      "backhand_index_pointing_left",
      "direction",
      "fingers",
      "hand",
      "left",
    ],
  },
  {
    emoji: "👉",
    keywords: [
      "backhand_index_pointing_right",
      "fingers",
      "hand",
      "direction",
      "right",
    ],
  },
  {
    emoji: "👆",
    keywords: [
      "backhand_index_pointing_up",
      "fingers",
      "hand",
      "direction",
      "up",
    ],
  },
  {
    emoji: "🖕",
    keywords: [
      "middle_finger",
      "hand",
      "fingers",
      "rude",
      "middle",
      "flipping",
    ],
  },
  {
    emoji: "👇",
    keywords: [
      "backhand_index_pointing_down",
      "fingers",
      "hand",
      "direction",
      "down",
    ],
  },
  {
    emoji: "☝️",
    keywords: ["index_pointing_up", "hand", "fingers", "direction", "up"],
  },
  {
    emoji: "👍",
    keywords: [
      "thumbs_up",
      "thumbsup",
      "yes",
      "awesome",
      "good",
      "agree",
      "accept",
      "cool",
      "hand",
      "like",
      "+1",
    ],
  },
  {
    emoji: "👎",
    keywords: ["thumbs_down", "thumbsdown", "no", "dislike", "hand", "-1"],
  },
  {
    emoji: "✊",
    keywords: ["raised_fist", "fingers", "hand", "grasp"],
  },
  {
    emoji: "👊",
    keywords: [
      "oncoming_fist",
      "angry",
      "violence",
      "fist",
      "hit",
      "attack",
      "hand",
    ],
  },
  {
    emoji: "🤛",
    keywords: ["left_facing_fist", "hand", "fistbump"],
  },
  {
    emoji: "🤜",
    keywords: ["right_facing_fist", "hand", "fistbump"],
  },
  {
    emoji: "👏",
    keywords: [
      "clapping_hands",
      "hands",
      "praise",
      "applause",
      "congrats",
      "yay",
    ],
  },
  {
    emoji: "🙌",
    keywords: [
      "raising_hands",
      "gesture",
      "hooray",
      "yea",
      "celebration",
      "hands",
    ],
  },
  {
    emoji: "👐",
    keywords: ["open_hands", "fingers", "butterfly", "hands", "open"],
  },
  {
    emoji: "🤲",
    keywords: ["palms_up_together", "hands", "gesture", "cupped", "prayer"],
  },
  {
    emoji: "🤝",
    keywords: ["handshake", "agreement", "shake"],
  },
  {
    emoji: "🙏",
    keywords: [
      "folded_hands",
      "please",
      "hope",
      "wish",
      "namaste",
      "highfive",
      "pray",
      "thank you",
      "thanks",
      "appreciate",
    ],
  },
  {
    emoji: "✍️",
    keywords: [
      "writing_hand",
      "lower_left_ballpoint_pen",
      "stationery",
      "write",
      "compose",
    ],
  },
  {
    emoji: "💅",
    keywords: [
      "nail_polish",
      "nail_care",
      "beauty",
      "manicure",
      "finger",
      "fashion",
      "nail",
      "slay",
    ],
  },
  {
    emoji: "🤳",
    keywords: ["selfie", "camera", "phone"],
  },
  {
    emoji: "💪",
    keywords: [
      "flexed_biceps",
      "arm",
      "flex",
      "hand",
      "summer",
      "strong",
      "biceps",
    ],
  },
  {
    emoji: "🦾",
    keywords: ["mechanical_arm", "accessibility"],
  },
  {
    emoji: "🦿",
    keywords: ["mechanical_leg", "accessibility"],
  },
  {
    emoji: "🦵",
    keywords: ["leg", "kick", "limb"],
  },
  {
    emoji: "🦶",
    keywords: ["foot", "kick", "stomp"],
  },
  {
    emoji: "👂",
    keywords: ["ear", "face", "hear", "sound", "listen"],
  },
  {
    emoji: "🦻",
    keywords: ["ear_with_hearing_aid", "accessibility"],
  },
  {
    emoji: "👃",
    keywords: ["nose", "smell", "sniff"],
  },
  {
    emoji: "🧠",
    keywords: ["brain", "smart", "intelligent"],
  },
  {
    emoji: "🦷",
    keywords: ["tooth", "teeth", "dentist"],
  },
  { emoji: "🦴", keywords: ["bone", "skeleton"] },
  {
    emoji: "👀",
    keywords: ["eyes", "look", "watch", "stalk", "peek", "see"],
  },
  {
    emoji: "👁️",
    keywords: ["eye", "face", "look", "see", "watch", "stare"],
  },
  {
    emoji: "👅",
    keywords: ["tongue", "mouth", "playful"],
  },
  { emoji: "👄", keywords: ["mouth", "kiss"] },
  {
    emoji: "👶",
    keywords: ["baby", "child", "boy", "girl", "toddler"],
  },
  {
    emoji: "🧒",
    keywords: ["child", "gender-neutral", "young"],
  },
  {
    emoji: "👦",
    keywords: ["boy", "man", "male", "guy", "teenager"],
  },
  {
    emoji: "👧",
    keywords: ["girl", "female", "woman", "teenager"],
  },
  {
    emoji: "🧑",
    keywords: ["person", "gender-neutral"],
  },
  {
    emoji: "👱",
    keywords: ["person_blond_hair", "hairstyle"],
  },
  {
    emoji: "👨",
    keywords: [
      "man",
      "mustache",
      "father",
      "dad",
      "guy",
      "classy",
      "sir",
      "moustache",
    ],
  },
  {
    emoji: "🧔",
    keywords: ["man_beard", "person", "bewhiskered"],
  },
  {
    emoji: "👨‍🦰",
    keywords: ["man_red_hair", "hairstyle"],
  },
  {
    emoji: "👨‍🦱",
    keywords: ["man_curly_hair", "hairstyle"],
  },
  {
    emoji: "👨‍🦳",
    keywords: ["man_white_hair", "old", "elder"],
  },
  {
    emoji: "👨‍🦲",
    keywords: ["man_bald", "hairless"],
  },
  {
    emoji: "👩",
    keywords: ["woman", "female", "girls", "lady"],
  },
  {
    emoji: "👩‍🦰",
    keywords: ["woman_red_hair", "hairstyle"],
  },
  {
    emoji: "🧑‍🦰",
    keywords: ["person_red_hair", "hairstyle"],
  },
  {
    emoji: "👩‍🦱",
    keywords: ["woman_curly_hair", "hairstyle"],
  },
  {
    emoji: "🧑‍🦱",
    keywords: ["person_curly_hair", "hairstyle"],
  },
  {
    emoji: "👩‍🦳",
    keywords: ["woman_white_hair", "old", "elder"],
  },
  {
    emoji: "🧑‍🦳",
    keywords: ["person_white_hair", "elder", "old"],
  },
  {
    emoji: "👩‍🦲",
    keywords: ["woman_bald", "hairless"],
  },
  {
    emoji: "🧑‍🦲",
    keywords: ["person_bald", "hairless"],
  },
  {
    emoji: "👱‍♀️",
    keywords: [
      "woman_blond_hair",
      "woman",
      "female",
      "girl",
      "blonde",
      "person",
    ],
  },
  {
    emoji: "👱‍♂️",
    keywords: [
      "man_blond_hair",
      "man",
      "male",
      "boy",
      "blonde",
      "guy",
      "person",
    ],
  },
  {
    emoji: "🧓",
    keywords: ["older_person", "human", "elder", "senior", "gender-neutral"],
  },
  {
    emoji: "👴",
    keywords: ["old_man", "human", "male", "men", "old", "elder", "senior"],
  },
  {
    emoji: "👵",
    keywords: [
      "old_woman",
      "human",
      "female",
      "women",
      "lady",
      "old",
      "elder",
      "senior",
    ],
  },
  {
    emoji: "🙍",
    keywords: ["person_frowning", "worried"],
  },
  {
    emoji: "🙍‍♂️",
    keywords: [
      "man_frowning",
      "male",
      "boy",
      "man",
      "sad",
      "depressed",
      "discouraged",
      "unhappy",
    ],
  },
  {
    emoji: "🙍‍♀️",
    keywords: [
      "woman_frowning",
      "female",
      "girl",
      "woman",
      "sad",
      "depressed",
      "discouraged",
      "unhappy",
    ],
  },
  {
    emoji: "🙎",
    keywords: ["person_pouting", "upset"],
  },
  {
    emoji: "🙎‍♂️",
    keywords: ["man_pouting", "male", "boy", "man"],
  },
  {
    emoji: "🙎‍♀️",
    keywords: ["woman_pouting", "female", "girl", "woman"],
  },
  {
    emoji: "🙅",
    keywords: ["person_gesturing_no", "decline"],
  },
  {
    emoji: "🙅‍♂️",
    keywords: ["man_gesturing_no", "male", "boy", "man", "nope"],
  },
  {
    emoji: "🙅‍♀️",
    keywords: ["woman_gesturing_no", "female", "girl", "woman", "nope"],
  },
  {
    emoji: "🙆",
    keywords: ["person_gesturing_ok", "agree"],
  },
  {
    emoji: "🙆‍♂️",
    keywords: [
      "man_gesturing_ok",
      "men",
      "boy",
      "male",
      "blue",
      "human",
      "man",
    ],
  },
  {
    emoji: "🙆‍♀️",
    keywords: [
      "woman_gesturing_ok",
      "women",
      "girl",
      "female",
      "pink",
      "human",
      "woman",
    ],
  },
  {
    emoji: "💁",
    keywords: ["person_tipping_hand", "information"],
  },
  {
    emoji: "💁‍♂️",
    keywords: [
      "man_tipping_hand",
      "male",
      "boy",
      "man",
      "human",
      "information",
    ],
  },
  {
    emoji: "💁‍♀️",
    keywords: [
      "woman_tipping_hand",
      "female",
      "girl",
      "woman",
      "human",
      "information",
    ],
  },
  {
    emoji: "🙋",
    keywords: ["person_raising_hand", "question"],
  },
  {
    emoji: "🙋‍♂️",
    keywords: ["man_raising_hand", "male", "boy", "man"],
  },
  {
    emoji: "🙋‍♀️",
    keywords: ["woman_raising_hand", "female", "girl", "woman"],
  },
  {
    emoji: "🧏",
    keywords: ["deaf_person", "accessibility"],
  },
  {
    emoji: "🧏‍♂️",
    keywords: ["deaf_man", "accessibility"],
  },
  {
    emoji: "🧏‍♀️",
    keywords: ["deaf_woman", "accessibility"],
  },
  {
    emoji: "🙇",
    keywords: ["person_bowing", "respectiful"],
  },
  {
    emoji: "🙇‍♂️",
    keywords: ["man_bowing", "man", "male", "boy"],
  },
  {
    emoji: "🙇‍♀️",
    keywords: ["woman_bowing", "woman", "female", "girl"],
  },
  {
    emoji: "🤦",
    keywords: ["person_facepalming", "disappointed"],
  },
  {
    emoji: "🤦‍♂️",
    keywords: ["man_facepalming", "man", "male", "boy", "disbelief"],
  },
  {
    emoji: "🤦‍♀️",
    keywords: ["woman_facepalming", "woman", "female", "girl", "disbelief"],
  },
  {
    emoji: "🤷",
    keywords: ["person_shrugging", "regardless"],
  },
  {
    emoji: "🤷‍♂️",
    keywords: [
      "man_shrugging",
      "man",
      "male",
      "boy",
      "confused",
      "indifferent",
      "doubt",
    ],
  },
  {
    emoji: "🤷‍♀️",
    keywords: [
      "woman_shrugging",
      "woman",
      "female",
      "girl",
      "confused",
      "indifferent",
      "doubt",
    ],
  },
  {
    emoji: "🧑‍⚕️",
    keywords: ["health_worker", "hospital"],
  },
  {
    emoji: "👨‍⚕️",
    keywords: [
      "man_health_worker",
      "doctor",
      "nurse",
      "therapist",
      "healthcare",
      "man",
      "human",
    ],
  },
  {
    emoji: "👩‍⚕️",
    keywords: [
      "woman_health_worker",
      "doctor",
      "nurse",
      "therapist",
      "healthcare",
      "woman",
      "human",
    ],
  },
  {
    emoji: "🧑‍🎓",
    keywords: ["student", "learn"],
  },
  {
    emoji: "👨‍🎓",
    keywords: ["man_student", "graduate", "man", "human"],
  },
  {
    emoji: "👩‍🎓",
    keywords: ["woman_student", "graduate", "woman", "human"],
  },
  {
    emoji: "🧑‍🏫",
    keywords: ["teacher", "professor"],
  },
  {
    emoji: "👨‍🏫",
    keywords: ["man_teacher", "instructor", "professor", "man", "human"],
  },
  {
    emoji: "👩‍🏫",
    keywords: ["woman_teacher", "instructor", "professor", "woman", "human"],
  },
  { emoji: "🧑‍⚖️", keywords: ["judge", "law"] },
  {
    emoji: "👨‍⚖️",
    keywords: ["man_judge", "justice", "court", "man", "human"],
  },
  {
    emoji: "👩‍⚖️",
    keywords: ["woman_judge", "justice", "court", "woman", "human"],
  },
  {
    emoji: "🧑‍🌾",
    keywords: ["farmer", "crops"],
  },
  {
    emoji: "👨‍🌾",
    keywords: ["man_farmer", "rancher", "gardener", "man", "human"],
  },
  {
    emoji: "👩‍🌾",
    keywords: ["woman_farmer", "rancher", "gardener", "woman", "human"],
  },
  {
    emoji: "🧑‍🍳",
    keywords: ["cook", "food", "kitchen", "culinary"],
  },
  {
    emoji: "👨‍🍳",
    keywords: ["man_cook", "chef", "man", "human"],
  },
  {
    emoji: "👩‍🍳",
    keywords: ["woman_cook", "chef", "woman", "human"],
  },
  {
    emoji: "🧑‍🔧",
    keywords: ["mechanic", "worker", "technician"],
  },
  {
    emoji: "👨‍🔧",
    keywords: ["man_mechanic", "plumber", "man", "human", "wrench"],
  },
  {
    emoji: "👩‍🔧",
    keywords: ["woman_mechanic", "plumber", "woman", "human", "wrench"],
  },
  {
    emoji: "🧑‍🏭",
    keywords: ["factory_worker", "labor"],
  },
  {
    emoji: "👨‍🏭",
    keywords: ["man_factory_worker", "assembly", "industrial", "man", "human"],
  },
  {
    emoji: "👩‍🏭",
    keywords: [
      "woman_factory_worker",
      "assembly",
      "industrial",
      "woman",
      "human",
    ],
  },
  {
    emoji: "🧑‍💼",
    keywords: ["office_worker", "business"],
  },
  {
    emoji: "👨‍💼",
    keywords: ["man_office_worker", "business", "manager", "man", "human"],
  },
  {
    emoji: "👩‍💼",
    keywords: ["woman_office_worker", "business", "manager", "woman", "human"],
  },
  {
    emoji: "🧑‍🔬",
    keywords: ["scientist", "chemistry"],
  },
  {
    emoji: "👨‍🔬",
    keywords: [
      "man_scientist",
      "biologist",
      "chemist",
      "engineer",
      "physicist",
      "man",
      "human",
    ],
  },
  {
    emoji: "👩‍🔬",
    keywords: [
      "woman_scientist",
      "biologist",
      "chemist",
      "engineer",
      "physicist",
      "woman",
      "human",
    ],
  },
  {
    emoji: "🧑‍💻",
    keywords: ["technologist", "computer"],
  },
  {
    emoji: "👨‍💻",
    keywords: [
      "man_technologist",
      "coder",
      "developer",
      "engineer",
      "programmer",
      "software",
      "man",
      "human",
      "laptop",
      "computer",
    ],
  },
  {
    emoji: "👩‍💻",
    keywords: [
      "woman_technologist",
      "coder",
      "developer",
      "engineer",
      "programmer",
      "software",
      "woman",
      "human",
      "laptop",
      "computer",
    ],
  },
  {
    emoji: "🧑‍🎤",
    keywords: ["singer", "song", "artist", "performer"],
  },
  {
    emoji: "👨‍🎤",
    keywords: ["man_singer", "rockstar", "entertainer", "man", "human"],
  },
  {
    emoji: "👩‍🎤",
    keywords: ["woman_singer", "rockstar", "entertainer", "woman", "human"],
  },
  {
    emoji: "🧑‍🎨",
    keywords: ["artist", "painting", "draw", "creativity"],
  },
  {
    emoji: "👨‍🎨",
    keywords: ["man_artist", "painter", "man", "human"],
  },
  {
    emoji: "👩‍🎨",
    keywords: ["woman_artist", "painter", "woman", "human"],
  },
  {
    emoji: "🧑‍✈️",
    keywords: ["pilot", "fly", "plane", "airplane"],
  },
  {
    emoji: "👨‍✈️",
    keywords: ["man_pilot", "aviator", "plane", "man", "human"],
  },
  {
    emoji: "👩‍✈️",
    keywords: ["woman_pilot", "aviator", "plane", "woman", "human"],
  },
  {
    emoji: "🧑‍🚀",
    keywords: ["astronaut", "outerspace"],
  },
  {
    emoji: "👨‍🚀",
    keywords: ["man_astronaut", "space", "rocket", "man", "human"],
  },
  {
    emoji: "👩‍🚀",
    keywords: ["woman_astronaut", "space", "rocket", "woman", "human"],
  },
  {
    emoji: "🧑‍🚒",
    keywords: ["firefighter", "fire"],
  },
  {
    emoji: "👨‍🚒",
    keywords: ["man_firefighter", "fireman", "man", "human"],
  },
  {
    emoji: "👩‍🚒",
    keywords: ["woman_firefighter", "fireman", "woman", "human"],
  },
  {
    emoji: "👮",
    keywords: ["police_officer", "cop"],
  },
  {
    emoji: "👮‍♂️",
    keywords: [
      "man_police_officer",
      "man",
      "police",
      "law",
      "legal",
      "enforcement",
      "arrest",
      "911",
    ],
  },
  {
    emoji: "👮‍♀️",
    keywords: [
      "woman_police_officer",
      "woman",
      "police",
      "law",
      "legal",
      "enforcement",
      "arrest",
      "911",
      "female",
    ],
  },
  {
    emoji: "🕵️",
    keywords: ["detective", "human", "spy"],
  },
  {
    emoji: "🕵️‍♂️",
    keywords: ["man_detective", "crime"],
  },
  {
    emoji: "🕵️‍♀️",
    keywords: [
      "woman_detective",
      "human",
      "spy",
      "detective",
      "female",
      "woman",
    ],
  },
  { emoji: "💂", keywords: ["guard", "protect"] },
  {
    emoji: "💂‍♂️",
    keywords: ["man_guard", "uk", "gb", "british", "male", "guy", "royal"],
  },
  {
    emoji: "💂‍♀️",
    keywords: [
      "woman_guard",
      "uk",
      "gb",
      "british",
      "female",
      "royal",
      "woman",
    ],
  },
  {
    emoji: "👷",
    keywords: ["construction_worker", "labor", "build"],
  },
  {
    emoji: "👷‍♂️",
    keywords: [
      "man_construction_worker",
      "male",
      "human",
      "wip",
      "guy",
      "build",
      "construction",
      "worker",
      "labor",
    ],
  },
  {
    emoji: "👷‍♀️",
    keywords: [
      "woman_construction_worker",
      "female",
      "human",
      "wip",
      "build",
      "construction",
      "worker",
      "labor",
      "woman",
    ],
  },
  {
    emoji: "🤴",
    keywords: ["prince", "boy", "man", "male", "crown", "royal", "king"],
  },
  {
    emoji: "👸",
    keywords: [
      "princess",
      "girl",
      "woman",
      "female",
      "blond",
      "crown",
      "royal",
      "queen",
    ],
  },
  {
    emoji: "👳",
    keywords: ["person_wearing_turban", "headdress"],
  },
  {
    emoji: "👳‍♂️",
    keywords: ["man_wearing_turban", "male", "indian", "hinduism", "arabs"],
  },
  {
    emoji: "👳‍♀️",
    keywords: [
      "woman_wearing_turban",
      "female",
      "indian",
      "hinduism",
      "arabs",
      "woman",
    ],
  },
  {
    emoji: "👲",
    keywords: ["man_with_skullcap", "male", "boy", "chinese"],
  },
  {
    emoji: "🧕",
    keywords: ["woman_with_headscarf", "female", "hijab", "mantilla", "tichel"],
  },
  {
    emoji: "🤵",
    keywords: ["man_in_tuxedo", "couple", "marriage", "wedding", "groom"],
  },
  {
    emoji: "👰",
    keywords: [
      "bride_with_veil",
      "couple",
      "marriage",
      "wedding",
      "woman",
      "bride",
    ],
  },
  {
    emoji: "🤰",
    keywords: ["pregnant_woman", "baby"],
  },
  {
    emoji: "🤱",
    keywords: ["breast_feeding", "nursing", "baby"],
  },
  {
    emoji: "👼",
    keywords: ["baby_angel", "heaven", "wings", "halo"],
  },
  {
    emoji: "🎅",
    keywords: [
      "santa_claus",
      "festival",
      "man",
      "male",
      "xmas",
      "father christmas",
    ],
  },
  {
    emoji: "🤶",
    keywords: ["mrs_claus", "woman", "female", "xmas", "mother christmas"],
  },
  {
    emoji: "🦸",
    keywords: ["superhero", "marvel"],
  },
  {
    emoji: "🦸‍♂️",
    keywords: ["man_superhero", "man", "male", "good", "hero", "superpowers"],
  },
  {
    emoji: "🦸‍♀️",
    keywords: [
      "woman_superhero",
      "woman",
      "female",
      "good",
      "heroine",
      "superpowers",
    ],
  },
  {
    emoji: "🦹",
    keywords: ["supervillain", "marvel"],
  },
  {
    emoji: "🦹‍♂️",
    keywords: [
      "man_supervillain",
      "man",
      "male",
      "evil",
      "bad",
      "criminal",
      "hero",
      "superpowers",
    ],
  },
  {
    emoji: "🦹‍♀️",
    keywords: [
      "woman_supervillain",
      "woman",
      "female",
      "evil",
      "bad",
      "criminal",
      "heroine",
      "superpowers",
    ],
  },
  { emoji: "🧙", keywords: ["mage", "magic"] },
  {
    emoji: "🧙‍♂️",
    keywords: ["man_mage", "man", "male", "mage", "sorcerer"],
  },
  {
    emoji: "🧙‍♀️",
    keywords: ["woman_mage", "woman", "female", "mage", "witch"],
  },
  {
    emoji: "🧚",
    keywords: ["fairy", "wings", "magical"],
  },
  {
    emoji: "🧚‍♂️",
    keywords: ["man_fairy", "man", "male"],
  },
  {
    emoji: "🧚‍♀️",
    keywords: ["woman_fairy", "woman", "female"],
  },
  {
    emoji: "🧛",
    keywords: ["vampire", "blood", "twilight"],
  },
  {
    emoji: "🧛‍♂️",
    keywords: ["man_vampire", "man", "male", "dracula"],
  },
  {
    emoji: "🧛‍♀️",
    keywords: ["woman_vampire", "woman", "female"],
  },
  { emoji: "🧜", keywords: ["merperson", "sea"] },
  {
    emoji: "🧜‍♂️",
    keywords: ["merman", "man", "male", "triton"],
  },
  {
    emoji: "🧜‍♀️",
    keywords: ["mermaid", "woman", "female", "merwoman", "ariel"],
  },
  { emoji: "🧝", keywords: ["elf", "magical"] },
  {
    emoji: "🧝‍♂️",
    keywords: ["man_elf", "man", "male"],
  },
  {
    emoji: "🧝‍♀️",
    keywords: ["woman_elf", "woman", "female"],
  },
  {
    emoji: "🧞",
    keywords: ["genie", "magical", "wishes"],
  },
  {
    emoji: "🧞‍♂️",
    keywords: ["man_genie", "man", "male"],
  },
  {
    emoji: "🧞‍♀️",
    keywords: ["woman_genie", "woman", "female"],
  },
  { emoji: "🧟", keywords: ["zombie", "dead"] },
  {
    emoji: "🧟‍♂️",
    keywords: [
      "man_zombie",
      "man",
      "male",
      "dracula",
      "undead",
      "walking dead",
    ],
  },
  {
    emoji: "🧟‍♀️",
    keywords: ["woman_zombie", "woman", "female", "undead", "walking dead"],
  },
  {
    emoji: "💆",
    keywords: ["person_getting_massage", "relax"],
  },
  {
    emoji: "💆‍♂️",
    keywords: ["man_getting_massage", "male", "boy", "man", "head"],
  },
  {
    emoji: "💆‍♀️",
    keywords: ["woman_getting_massage", "female", "girl", "woman", "head"],
  },
  {
    emoji: "💇",
    keywords: ["person_getting_haircut", "hairstyle"],
  },
  {
    emoji: "💇‍♂️",
    keywords: ["man_getting_haircut", "male", "boy", "man"],
  },
  {
    emoji: "💇‍♀️",
    keywords: ["woman_getting_haircut", "female", "girl", "woman"],
  },
  {
    emoji: "🚶",
    keywords: ["person_walking", "move"],
  },
  {
    emoji: "🚶‍♂️",
    keywords: ["man_walking", "human", "feet", "steps"],
  },
  {
    emoji: "🚶‍♀️",
    keywords: ["woman_walking", "human", "feet", "steps", "woman", "female"],
  },
  {
    emoji: "🧍",
    keywords: ["person_standing", "still"],
  },
  {
    emoji: "🧍‍♂️",
    keywords: ["man_standing", "still"],
  },
  {
    emoji: "🧍‍♀️",
    keywords: ["woman_standing", "still"],
  },
  {
    emoji: "🧎",
    keywords: ["person_kneeling", "pray", "respectful"],
  },
  {
    emoji: "🧎‍♂️",
    keywords: ["man_kneeling", "pray", "respectful"],
  },
  {
    emoji: "🧎‍♀️",
    keywords: ["woman_kneeling", "respectful", "pray"],
  },
  {
    emoji: "🧑‍🦯",
    keywords: ["person_with_probing_cane", "blind"],
  },
  {
    emoji: "👨‍🦯",
    keywords: ["man_with_probing_cane", "blind"],
  },
  {
    emoji: "👩‍🦯",
    keywords: ["woman_with_probing_cane", "blind"],
  },
  {
    emoji: "🧑‍🦼",
    keywords: ["person_in_motorized_wheelchair", "disability", "accessibility"],
  },
  {
    emoji: "👨‍🦼",
    keywords: ["man_in_motorized_wheelchair", "disability", "accessibility"],
  },
  {
    emoji: "👩‍🦼",
    keywords: ["woman_in_motorized_wheelchair", "disability", "accessibility"],
  },
  {
    emoji: "🧑‍🦽",
    keywords: ["person_in_manual_wheelchair", "disability", "accessibility"],
  },
  {
    emoji: "👨‍🦽",
    keywords: ["man_in_manual_wheelchair", "disability", "accessibility"],
  },
  {
    emoji: "👩‍🦽",
    keywords: ["woman_in_manual_wheelchair", "disability", "accessibility"],
  },
  {
    emoji: "🏃",
    keywords: ["person_running", "move"],
  },
  {
    emoji: "🏃‍♂️",
    keywords: ["man_running", "man", "walking", "exercise", "race", "running"],
  },
  {
    emoji: "🏃‍♀️",
    keywords: [
      "woman_running",
      "woman",
      "walking",
      "exercise",
      "race",
      "running",
      "female",
    ],
  },
  {
    emoji: "💃",
    keywords: ["woman_dancing", "female", "girl", "woman", "fun"],
  },
  {
    emoji: "🕺",
    keywords: ["man_dancing", "male", "boy", "fun", "dancer"],
  },
  {
    emoji: "🕴️",
    keywords: [
      "man_in_suit_levitating",
      "suit",
      "business",
      "levitate",
      "hover",
      "jump",
    ],
  },
  {
    emoji: "👯",
    keywords: ["people_with_bunny_ears", "perform", "costume"],
  },
  {
    emoji: "👯‍♂️",
    keywords: ["men_with_bunny_ears", "male", "bunny", "men", "boys"],
  },
  {
    emoji: "👯‍♀️",
    keywords: ["women_with_bunny_ears", "female", "bunny", "women", "girls"],
  },
  {
    emoji: "🧖",
    keywords: ["person_in_steamy_room", "relax", "spa"],
  },
  {
    emoji: "🧖‍♂️",
    keywords: [
      "man_in_steamy_room",
      "male",
      "man",
      "spa",
      "steamroom",
      "sauna",
    ],
  },
  {
    emoji: "🧖‍♀️",
    keywords: [
      "woman_in_steamy_room",
      "female",
      "woman",
      "spa",
      "steamroom",
      "sauna",
    ],
  },
  {
    emoji: "🧗",
    keywords: ["person_climbing", "sport"],
  },
  {
    emoji: "🧗‍♂️",
    keywords: ["man_climbing", "sports", "hobby", "man", "male", "rock"],
  },
  {
    emoji: "🧗‍♀️",
    keywords: ["woman_climbing", "sports", "hobby", "woman", "female", "rock"],
  },
  {
    emoji: "🤺",
    keywords: ["person_fencing", "sports", "fencing", "sword"],
  },
  {
    emoji: "🏇",
    keywords: [
      "horse_racing",
      "animal",
      "betting",
      "competition",
      "gambling",
      "luck",
    ],
  },
  {
    emoji: "⛷️",
    keywords: ["skier", "sports", "winter", "snow"],
  },
  {
    emoji: "🏂",
    keywords: ["snowboarder", "sports", "winter"],
  },
  {
    emoji: "🏌️",
    keywords: ["person_golfing", "sports", "business"],
  },
  {
    emoji: "🏌️‍♂️",
    keywords: ["man_golfing", "sport"],
  },
  {
    emoji: "🏌️‍♀️",
    keywords: ["woman_golfing", "sports", "business", "woman", "female"],
  },
  {
    emoji: "🏄",
    keywords: ["person_surfing", "sport", "sea"],
  },
  {
    emoji: "🏄‍♂️",
    keywords: ["man_surfing", "sports", "ocean", "sea", "summer", "beach"],
  },
  {
    emoji: "🏄‍♀️",
    keywords: [
      "woman_surfing",
      "sports",
      "ocean",
      "sea",
      "summer",
      "beach",
      "woman",
      "female",
    ],
  },
  {
    emoji: "🚣",
    keywords: ["person_rowing_boat", "sport", "move"],
  },
  {
    emoji: "🚣‍♂️",
    keywords: ["man_rowing_boat", "sports", "hobby", "water", "ship"],
  },
  {
    emoji: "🚣‍♀️",
    keywords: [
      "woman_rowing_boat",
      "sports",
      "hobby",
      "water",
      "ship",
      "woman",
      "female",
    ],
  },
  {
    emoji: "🏊",
    keywords: ["person_swimming", "sport", "pool"],
  },
  {
    emoji: "🏊‍♂️",
    keywords: [
      "man_swimming",
      "sports",
      "exercise",
      "human",
      "athlete",
      "water",
      "summer",
    ],
  },
  {
    emoji: "🏊‍♀️",
    keywords: [
      "woman_swimming",
      "sports",
      "exercise",
      "human",
      "athlete",
      "water",
      "summer",
      "woman",
      "female",
    ],
  },
  {
    emoji: "⛹️",
    keywords: ["person_bouncing_ball", "sports", "human"],
  },
  {
    emoji: "⛹️‍♂️",
    keywords: ["man_bouncing_ball", "sport"],
  },
  {
    emoji: "⛹️‍♀️",
    keywords: ["woman_bouncing_ball", "sports", "human", "woman", "female"],
  },
  {
    emoji: "🏋️",
    keywords: ["person_lifting_weights", "sports", "training", "exercise"],
  },
  {
    emoji: "🏋️‍♂️",
    keywords: ["man_lifting_weights", "sport"],
  },
  {
    emoji: "🏋️‍♀️",
    keywords: [
      "woman_lifting_weights",
      "sports",
      "training",
      "exercise",
      "woman",
      "female",
    ],
  },
  {
    emoji: "🚴",
    keywords: ["person_biking", "bicycle", "bike", "cyclist", "sport", "move"],
  },
  {
    emoji: "🚴‍♂️",
    keywords: [
      "man_biking",
      "bicycle",
      "bike",
      "cyclist",
      "sports",
      "exercise",
      "hipster",
    ],
  },
  {
    emoji: "🚴‍♀️",
    keywords: [
      "woman_biking",
      "bicycle",
      "bike",
      "cyclist",
      "sports",
      "exercise",
      "hipster",
      "woman",
      "female",
    ],
  },
  {
    emoji: "🚵",
    keywords: [
      "person_mountain_biking",
      "bicycle",
      "bike",
      "cyclist",
      "sport",
      "move",
    ],
  },
  {
    emoji: "🚵‍♂️",
    keywords: [
      "man_mountain_biking",
      "bicycle",
      "bike",
      "cyclist",
      "transportation",
      "sports",
      "human",
      "race",
    ],
  },
  {
    emoji: "🚵‍♀️",
    keywords: [
      "woman_mountain_biking",
      "bicycle",
      "bike",
      "cyclist",
      "transportation",
      "sports",
      "human",
      "race",
      "woman",
      "female",
    ],
  },
  {
    emoji: "🤸",
    keywords: ["person_cartwheeling", "sport", "gymnastic"],
  },
  {
    emoji: "🤸‍♂️",
    keywords: ["man_cartwheeling", "gymnastics"],
  },
  {
    emoji: "🤸‍♀️",
    keywords: ["woman_cartwheeling", "gymnastics"],
  },
  {
    emoji: "🤼",
    keywords: ["people_wrestling", "sport"],
  },
  {
    emoji: "🤼‍♂️",
    keywords: ["men_wrestling", "sports", "wrestlers"],
  },
  {
    emoji: "🤼‍♀️",
    keywords: ["women_wrestling", "sports", "wrestlers"],
  },
  {
    emoji: "🤽",
    keywords: ["person_playing_water_polo", "sport"],
  },
  {
    emoji: "🤽‍♂️",
    keywords: ["man_playing_water_polo", "sports", "pool"],
  },
  {
    emoji: "🤽‍♀️",
    keywords: ["woman_playing_water_polo", "sports", "pool"],
  },
  {
    emoji: "🤾",
    keywords: ["person_playing_handball", "sport"],
  },
  {
    emoji: "🤾‍♂️",
    keywords: ["man_playing_handball", "sports"],
  },
  {
    emoji: "🤾‍♀️",
    keywords: ["woman_playing_handball", "sports"],
  },
  {
    emoji: "🤹",
    keywords: ["person_juggling", "performance", "balance"],
  },
  {
    emoji: "🤹‍♂️",
    keywords: ["man_juggling", "juggle", "balance", "skill", "multitask"],
  },
  {
    emoji: "🤹‍♀️",
    keywords: ["woman_juggling", "juggle", "balance", "skill", "multitask"],
  },
  {
    emoji: "🧘",
    keywords: ["person_in_lotus_position", "meditate"],
  },
  {
    emoji: "🧘‍♂️",
    keywords: [
      "man_in_lotus_position",
      "man",
      "male",
      "meditation",
      "yoga",
      "serenity",
      "zen",
      "mindfulness",
    ],
  },
  {
    emoji: "🧘‍♀️",
    keywords: [
      "woman_in_lotus_position",
      "woman",
      "female",
      "meditation",
      "yoga",
      "serenity",
      "zen",
      "mindfulness",
    ],
  },
  {
    emoji: "🛀",
    keywords: ["person_taking_bath", "clean", "shower", "bathroom"],
  },
  {
    emoji: "🛌",
    keywords: ["person_in_bed", "bed", "rest"],
  },
  {
    emoji: "🧑‍🤝‍🧑",
    keywords: ["people_holding_hands", "friendship"],
  },
  {
    emoji: "👭",
    keywords: [
      "women_holding_hands",
      "pair",
      "friendship",
      "couple",
      "love",
      "like",
      "female",
      "people",
      "human",
    ],
  },
  {
    emoji: "👫",
    keywords: [
      "woman_and_man_holding_hands",
      "pair",
      "people",
      "human",
      "love",
      "date",
      "dating",
      "like",
      "affection",
      "valentines",
      "marriage",
    ],
  },
  {
    emoji: "👬",
    keywords: [
      "men_holding_hands",
      "pair",
      "couple",
      "love",
      "like",
      "bromance",
      "friendship",
      "people",
      "human",
    ],
  },
  {
    emoji: "💏",
    keywords: [
      "kiss",
      "pair",
      "valentines",
      "love",
      "like",
      "dating",
      "marriage",
    ],
  },
  {
    emoji: "👩‍❤️‍💋‍👨",
    keywords: ["kiss_woman_man", "love"],
  },
  {
    emoji: "👨‍❤️‍💋‍👨",
    keywords: [
      "kiss_man_man",
      "pair",
      "valentines",
      "love",
      "like",
      "dating",
      "marriage",
    ],
  },
  {
    emoji: "👩‍❤️‍💋‍👩",
    keywords: [
      "kiss_woman_woman",
      "pair",
      "valentines",
      "love",
      "like",
      "dating",
      "marriage",
    ],
  },
  {
    emoji: "💑",
    keywords: [
      "couple_with_heart",
      "pair",
      "love",
      "like",
      "affection",
      "human",
      "dating",
      "valentines",
      "marriage",
    ],
  },
  {
    emoji: "👩‍❤️‍👨",
    keywords: ["couple_with_heart_woman_man", "love"],
  },
  {
    emoji: "👨‍❤️‍👨",
    keywords: [
      "couple_with_heart_man_man",
      "pair",
      "love",
      "like",
      "affection",
      "human",
      "dating",
      "valentines",
      "marriage",
    ],
  },
  {
    emoji: "👩‍❤️‍👩",
    keywords: [
      "couple_with_heart_woman_woman",
      "pair",
      "love",
      "like",
      "affection",
      "human",
      "dating",
      "valentines",
      "marriage",
    ],
  },
  {
    emoji: "👪",
    keywords: [
      "family",
      "home",
      "parents",
      "child",
      "mom",
      "dad",
      "father",
      "mother",
      "people",
      "human",
    ],
  },
  {
    emoji: "👨‍👩‍👦",
    keywords: ["family_man_woman_boy", "love"],
  },
  {
    emoji: "👨‍👩‍👧",
    keywords: [
      "family_man_woman_girl",
      "home",
      "parents",
      "people",
      "human",
      "child",
    ],
  },
  {
    emoji: "👨‍👩‍👧‍👦",
    keywords: [
      "family_man_woman_girl_boy",
      "home",
      "parents",
      "people",
      "human",
      "children",
    ],
  },
  {
    emoji: "👨‍👩‍👦‍👦",
    keywords: [
      "family_man_woman_boy_boy",
      "home",
      "parents",
      "people",
      "human",
      "children",
    ],
  },
  {
    emoji: "👨‍👩‍👧‍👧",
    keywords: [
      "family_man_woman_girl_girl",
      "home",
      "parents",
      "people",
      "human",
      "children",
    ],
  },
  {
    emoji: "👨‍👨‍👦",
    keywords: [
      "family_man_man_boy",
      "home",
      "parents",
      "people",
      "human",
      "children",
    ],
  },
  {
    emoji: "👨‍👨‍👧",
    keywords: [
      "family_man_man_girl",
      "home",
      "parents",
      "people",
      "human",
      "children",
    ],
  },
  {
    emoji: "👨‍👨‍👧‍👦",
    keywords: [
      "family_man_man_girl_boy",
      "home",
      "parents",
      "people",
      "human",
      "children",
    ],
  },
  {
    emoji: "👨‍👨‍👦‍👦",
    keywords: [
      "family_man_man_boy_boy",
      "home",
      "parents",
      "people",
      "human",
      "children",
    ],
  },
  {
    emoji: "👨‍👨‍👧‍👧",
    keywords: [
      "family_man_man_girl_girl",
      "home",
      "parents",
      "people",
      "human",
      "children",
    ],
  },
  {
    emoji: "👩‍👩‍👦",
    keywords: [
      "family_woman_woman_boy",
      "home",
      "parents",
      "people",
      "human",
      "children",
    ],
  },
  {
    emoji: "👩‍👩‍👧",
    keywords: [
      "family_woman_woman_girl",
      "home",
      "parents",
      "people",
      "human",
      "children",
    ],
  },
  {
    emoji: "👩‍👩‍👧‍👦",
    keywords: [
      "family_woman_woman_girl_boy",
      "home",
      "parents",
      "people",
      "human",
      "children",
    ],
  },
  {
    emoji: "👩‍👩‍👦‍👦",
    keywords: [
      "family_woman_woman_boy_boy",
      "home",
      "parents",
      "people",
      "human",
      "children",
    ],
  },
  {
    emoji: "👩‍👩‍👧‍👧",
    keywords: [
      "family_woman_woman_girl_girl",
      "home",
      "parents",
      "people",
      "human",
      "children",
    ],
  },
  {
    emoji: "👨‍👦",
    keywords: ["family_man_boy", "home", "parent", "people", "human", "child"],
  },
  {
    emoji: "👨‍👦‍👦",
    keywords: [
      "family_man_boy_boy",
      "home",
      "parent",
      "people",
      "human",
      "children",
    ],
  },
  {
    emoji: "👨‍👧",
    keywords: ["family_man_girl", "home", "parent", "people", "human", "child"],
  },
  {
    emoji: "👨‍👧‍👦",
    keywords: [
      "family_man_girl_boy",
      "home",
      "parent",
      "people",
      "human",
      "children",
    ],
  },
  {
    emoji: "👨‍👧‍👧",
    keywords: [
      "family_man_girl_girl",
      "home",
      "parent",
      "people",
      "human",
      "children",
    ],
  },
  {
    emoji: "👩‍👦",
    keywords: [
      "family_woman_boy",
      "home",
      "parent",
      "people",
      "human",
      "child",
    ],
  },
  {
    emoji: "👩‍👦‍👦",
    keywords: [
      "family_woman_boy_boy",
      "home",
      "parent",
      "people",
      "human",
      "children",
    ],
  },
  {
    emoji: "👩‍👧",
    keywords: [
      "family_woman_girl",
      "home",
      "parent",
      "people",
      "human",
      "child",
    ],
  },
  {
    emoji: "👩‍👧‍👦",
    keywords: [
      "family_woman_girl_boy",
      "home",
      "parent",
      "people",
      "human",
      "children",
    ],
  },
  {
    emoji: "👩‍👧‍👧",
    keywords: [
      "family_woman_girl_girl",
      "home",
      "parent",
      "people",
      "human",
      "children",
    ],
  },
  {
    emoji: "🗣️",
    keywords: [
      "speaking_head",
      "user",
      "person",
      "human",
      "sing",
      "say",
      "talk",
    ],
  },
  {
    emoji: "👤",
    keywords: ["bust_in_silhouette", "user", "person", "human"],
  },
  {
    emoji: "👥",
    keywords: [
      "busts_in_silhouette",
      "user",
      "person",
      "human",
      "group",
      "team",
    ],
  },
  {
    emoji: "👣",
    keywords: ["footprints", "feet", "tracking", "walking", "beach"],
  },
  {
    emoji: "🐵",
    keywords: ["monkey_face", "animal", "nature", "circus"],
  },
  {
    emoji: "🐒",
    keywords: ["monkey", "animal", "nature", "banana", "circus"],
  },
  {
    emoji: "🦍",
    keywords: ["gorilla", "animal", "nature", "circus"],
  },
  {
    emoji: "🦧",
    keywords: ["orangutan", "animal"],
  },
  {
    emoji: "🐶",
    keywords: [
      "dog_face",
      "animal",
      "friend",
      "nature",
      "woof",
      "puppy",
      "pet",
      "faithful",
    ],
  },
  {
    emoji: "🐕",
    keywords: ["dog", "animal", "nature", "friend", "doge", "pet", "faithful"],
  },
  {
    emoji: "🦮",
    keywords: ["guide_dog", "animal", "blind"],
  },
  {
    emoji: "🐕‍🦺",
    keywords: ["service_dog", "blind", "animal"],
  },
  {
    emoji: "🐩",
    keywords: ["poodle", "dog", "animal", "101", "nature", "pet"],
  },
  {
    emoji: "🐺",
    keywords: ["wolf", "animal", "nature", "wild"],
  },
  {
    emoji: "🦊",
    keywords: ["fox", "animal", "nature", "face"],
  },
  {
    emoji: "🦝",
    keywords: ["raccoon", "animal", "nature"],
  },
  {
    emoji: "🐱",
    keywords: ["cat_face", "animal", "meow", "nature", "pet", "kitten"],
  },
];
